### ISSUE TITLE
Support to Vue 3

### ISSUE THREAD

**Issue by dealenx** [vycoder/vue-animate-onscroll#17]
I have tested at nuxt v2 and nuxt-bridge, 

It works better than aos and sal.js(https://github.com/mciastek/sal/issues/63), but it does not support at Vue 3. 

Do you intend to upgrade?

CodeSandBox with Vue 3: https://codesandbox.io/s/vue3-and-vue-animate-onscroll-9cst9
CodeSandBox with Vue 2: https://codesandbox.io/s/vue2-and-vue-animate-onscroll-giezv

**Comment by dealenx** [comment]
CodeSandBox with Vue 3: codesandbox.io/s/vue3-and-vue-animate-onscroll-9cst9
CodeSandBox with Vue 2: https://codesandbox.io/s/vue2-and-vue-animate-onscroll-giezv

**Comment by vycoder** [comment]
I will just haven't had the time to work on it.

**Comment by dealenx** [comment]
Okay, no problem 

Today i have tried to make vue3 support based [on this topic](https://stackoverflow.com/questions/63869859/migrating-detect-click-outside-custom-directive-from-vue-2-to-vue-3)  and it didn't work. Need more time to explore the issue.

**Comment by lindaifu** [comment]
for vue3: vue3-animate-onscroll
[https://www.npmjs.com/package/vue3-animate-onscrol](https://www.npmjs.com/package/vue3-animate-onscrol)

**Comment by dealenx** [comment]
> for vue3: vue3-animate-onscroll https://www.npmjs.com/package/vue3-animate-onscrol

Thanks!

I didn't check the `vue3-animate-onscroll` library, but i will close this issue topic.
